{% set version = "1.3-8" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-cobs
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/cobs_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/cobs/cobs_{{ version }}.tar.gz
  sha256: 2c2049c7cb868a2e4e1a530fe7218fac56e6157ef64ad57b91c5bb457dbc9821

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-sparsem >=1.6
    - r-quantreg >=4.65
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-sparsem >=1.6
    - r-quantreg >=4.65

test:
  commands:
    - $R -e "library('cobs')"           # [not win]
    - "\"%R%\" -e \"library('cobs')\""  # [win]

about:
  home: http://curves-etc.r-forge.r-project.org/ http://r-forge.r-project.org/R/?group_id=846
  license: GPL-2.0-or-later
  summary: Qualitatively Constrained (Regression) Smoothing Splines via Linear Programming and Sparse Matrices.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: cobs
# Version: 1.3-4
# VersionNote: Released 1.3-3 on 2017-03-29
# Date: 2020-01-20
# Title: Constrained B-Splines (Sparse Matrix Based)
# Description: Qualitatively Constrained (Regression) Smoothing Splines via Linear Programming and Sparse Matrices.
# Author: Pin T. Ng <Pin.Ng@nau.edu> and Martin Maechler
# Maintainer: Martin Maechler <maechler@stat.math.ethz.ch>
# Imports: SparseM (>= 1.6), quantreg (>= 4.65), grDevices, graphics, splines, stats, methods
# Suggests: Matrix
# LazyData: yes
# BuildResaveData: no
# URL: http://curves-etc.r-forge.r-project.org/ http://r-forge.r-project.org/R/?group_id=846
# License: GPL (>= 2)
# NeedsCompilation: yes
# Packaged: 2020-01-20 16:53:29 UTC; maechler
# Repository: CRAN
# Date/Publication: 2020-01-24 14:20:07 UTC
