travis:
  secure:
    BINSTAR_TOKEN: km530p/PDK0CNRGCEcZzMOeP3nxI0ViH+aCPP9UaYrGbrhrJs26VScsl/jH6vfli1z59wcSuzXWZsN+/LLDsPKNVBJADmi5HlA5l4ssvtMn8kpc8Sb7fIRNDoR+/PCkBqdJ6OrlppjXhsBQ0V/jZv91adu0tbAb5n/OiOL3AceUvy4orZljia/SCQD28nyNqZy2kg6GsfZSEhq8jHNC9dF7hsdeawiDX0Hn0X4PGRGlt3TsDKL3w1uYFmsA9kFlTjmMMlGSdVilUrVsinVUBSIB7LPHtLMnuzzMHtXs+ZXEyuJeaWj7sHu9hu30XXq7Qt9UH68xRQShSByskcKq9HxaAAX4t9dwTdm1zZz2LxwE6hq6xo7M4XsWTHU1AFfzKBGwFmkGwudrTgyav5iow/lKFNnPbOzpJgWXgwHM0qt6d274aDB9LSMI1uk4v3sA+AwDcZP9P6xwoc0izVnB0Kqoz2c+H/EGB6SjpQ37IqWY69ucupmvbp2I3X73xz4MoBKXRJKx+QHMgByowTmmTisAXnFfVTe7Hwc81XsScvpt2rlufkisKlFn+5ASebt8XmUgvVPDZfjAXCgGJAMWWD1biiI8yMm+qyDG8Z5zwPPKoIzGkBT+IJlEoALla5gfls2z/3fnebraFYpGpdxk3fxuQkOt7zKqVzc92n5G29K8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
