appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: BmXy1VQZgzafMrPdniFCY0B/w0AlYr8gTAXYbciRnQd9M3nRTaNd2NMCDdnt9XnzSZUdN8MWDLbdzMxMbloEe/TTqXrkwpN5z1SY+w819dvNVyNo1jYjiIndgZrAY4GCp1bky44FY+rrJjUCAheKx8TsRZctz7+Zjs8ePEN6wsKT55U9qOq4aCWGkO2KjJWGStjc++ibpo2JhrO9wJukjF3L9oPUtZaU1ig+aVlOynG+6fEC5gTsFV0trJQn8x7zF0wXXgkFzCjXfbfSeUw+MOfUJPouTkYAdBdDzbYHcCeThFeUni+tVmaVnirqH6zqModJ/1OhoXOK4RPsgHab76O38UMxs9zLSn6IE4qnlSUJULYZlL4iRTu5kgCjCtdgwtS9LP3xoFVkKW7pZpCsueNKrSmJ9BU55tzC6pAWYMRZvr2kBYw1JYGcWiGlAWxc/Bb+++s42gXx7JfkXjRAlKHjF/doACvnGQsDtFjARyvuYXu5I3XwQGtJywwR0pGv0HvaD+8DDyTTaBkVoMUbvWUaFJf4/PTBi1SWL/liEYJqHFHkM7sr/JgfmxmoOyL+y5ZWAiWTZvre8Rhz4mkoYeN3LXeYtsw6p0wYfoL/LGI42vxz7CNgHnYPLo72x1TR2OxwxzmKAC3bgYAnilnp8tJ9tsrEP40z+XVf+Ptldk8=}
